---
- name: Download deployer.phar
  get_url: url="{{ deployer_in_url }}" dest="{{ deployer_in_path }}"

- name: Make deployer.phar executable
  file: path="{{ deployer_in_path }}" state=file mode=755